add forEach method
kuroljov/triematch pull request #3
Opened 2017-09-03 13:36 UTC by danilbeltsov

2017-09-03 14:02 UTC, viktor-ku requested changes

2017-09-03 14:02 UTC, kuroljov commented on src/Trie.js
> +   @example store.forEach(callback())
```js
store.forEach(callback)
```

Обрати внимание на то, что твой callback не должен вызываться перед тем как отправиться в `forEach`.

Это может произойти, но для примера это слишком сложно

2017-09-03 14:02 UTC, kuroljov commented on src/Trie.js
> +   @example store.forEach(function(value, key, table) {
Замени на стрелочнцю функцию

2017-09-03 14:02 UTC, kuroljov commented on src/Trie.js
> +  forEach (callback: (value: any, key: any, table: any) => any, thisArg: any): void {
`key`, `table` и `thisArg` не `any`. У них есть определенный тип.
`thisArg` скорее всего будет объект.

2017-09-03 14:02 UTC, kuroljov commented on src/Trie.js
> +    var keys = Object.keys(this.table)
`var` замени на `const` или `ket`. Старайся использзовать `let` только там, где точно не будет переопеределений и соответственно старайся не переопределять (redefine)

2017-09-03 14:02 UTC, kuroljov commented on src/Trie.js
> +      callback.call(thisArg, value, key, this)
Не стоит передавать `this` в конце, поскольку это все-таки instance, а тебе нужно передать итерируемый объект, то есть `table`. Желательно передавать не ссылку на `this.table`

2017-09-03 14:02 UTC, kuroljov commented on src/Trie.js
> +  }
Добавить пробел

2017-09-05 17:40 UTC, danilbeltsov commented on src/Trie.js
> +   @example store.forEach(callback())
> Обрати внимание на то, что твой callback не должен вызываться перед тем как отправиться в forEach.

2017-09-05 17:41 UTC, danilbeltsov commented on src/Trie.js
> +  }
41 строчка?

2017-09-05 17:44 UTC, kuroljov commented on src/Trie.js
> +   @example store.forEach(callback())
Сейчас ты сначала исполняешь `callback`, а результат исполнения (что тоже является функцией по видимости) уже отправляешь в `forEach`.

Это называется Higher Order Functions и это то, что тебе сейчас не нужно. И вообще в этом примере не нужно усложнять.

2017-09-05 17:45 UTC, kuroljov commented on src/Trie.js
> +  }
Если ты добавишь пробел после 41, то eslint тебя съест. Пробел нужно добавить после 42. Посмотри на остальные методы, там вроде везде пробел после метода?

2017-09-05 17:46 UTC, danilbeltsov commented on src/Trie.js
> +   @example store.forEach(callback())
а, кажись понял, Просто в issue была задача реализовать метод схожий с тем что у Map. А по ссылке в MDN написано: `myMap.forEach(callback[, thisArg])`  вот я этот коллбек как функцию и передал

2017-09-05 17:48 UTC, kuroljov commented on src/Trie.js
> +   @example store.forEach(callback())
Там написано правильно, просто ты немного не так поянл. Через `[,thisArg]` обозначается опциональный параметр и это не имеет ничего общего с параметром `callback`

2017-09-05 17:57 UTC, kuroljov commented on src/Trie.js
> +   @example store.forEach(callback())
Для закрепления

```js
function logItem (value, key) {
  console.log(key, '=>', value)
}

store.forEach(logItem)
```

2017-09-06 19:30 UTC, viktor-ku requested changes

2017-09-06 19:30 UTC, kuroljov commented on src/Trie.js
> +  }
Проверь MDN снова. Нехватает последнего аргумента., а также напутан порядок передачи аргументов в `callback`

Зачем внутри цикла `let`? Сдесь `let` нужен только для `i`

2017-09-08 18:37 UTC, viktor-ku requested changes

2017-09-08 18:37 UTC, kuroljov commented on test/forEach.js
> +  t.test('empty callback', t => {
Хорошо, что ты написал что-то, однако этот кейс не тестирует ничего. Что ты хотел этим кейсом проверить?

2017-09-08 18:37 UTC, kuroljov commented on test/forEach.js
> +    t.notOk(store.forEach(null))
`forEach` в любом случае ничего не возвращает же?

2017-09-08 18:37 UTC, kuroljov commented on test/forEach.js
> +    t.notOk(store.forEach(function (key, value, table, garbage) {}))
Опять же ты ничего этим не тестрируешь

2017-09-08 18:39 UTC, kuroljov commented
```js

```

2017-09-08 18:40 UTC, kuroljov commented
Случайно закрыл. Снова открыл, все ок

2017-09-15 17:41 UTC, closed without merging